// Default service catalog entries for Petasync
// These can be seeded into the database via the ServiceCatalog admin page

export interface DefaultService {
  name: string;
  description: string;
  category: string;
  default_price: number;
  unit: string;
  is_active: boolean;
  sort_order: number;
}

export const SERVICE_CATEGORIES = [
  'Privatkunden',
  'Geschäftskunden',
  'Webdesign',
  'Sonstiges',
] as const;

export type ServiceCategory = typeof SERVICE_CATEGORIES[number];

export const DEFAULT_SERVICES: DefaultService[] = [
  // =====================================================
  // PRIVATKUNDEN
  // =====================================================
  {
    name: 'Diagnose & Fehleranalyse',
    description: 'Professionelle Fehleranalyse Ihres Computers – wir finden das Problem schnell und zuverlässig. Inkl. Hardware-Check, Software-Analyse und Fehlerprotokoll.',
    category: 'Privatkunden',
    default_price: 0,
    unit: 'pauschal',
    is_active: true,
    sort_order: 1,
  },
  {
    name: 'PC Reinigung',
    description: 'Professionelle Reinigung für bessere Leistung und längere Lebensdauer. Ihr PC wird wieder leise und kühl. Inkl. Innen- & Außenreinigung, Lüfter-Wartung, Wärmeleitpaste erneuern.',
    category: 'Privatkunden',
    default_price: 25,
    unit: 'pauschal',
    is_active: true,
    sort_order: 2,
  },
  {
    name: 'PC Reparatur',
    description: 'Schnelle Diagnose und professionelle Reparatur aller gängigen Marken und Modelle. Display-Austausch, Tastatur-Reparatur, Akku-Wechsel, Mainboard-Reparatur.',
    category: 'Privatkunden',
    default_price: 49,
    unit: 'Std.',
    is_active: true,
    sort_order: 3,
  },
  {
    name: 'Laptop Reparatur',
    description: 'Professionelle Laptop-Reparatur: Display-Austausch, Tastatur-Reparatur, Akku-Wechsel, Mainboard-Reparatur.',
    category: 'Privatkunden',
    default_price: 49,
    unit: 'Std.',
    is_active: true,
    sort_order: 4,
  },
  {
    name: 'Datenrettung',
    description: 'Professionelle Wiederherstellung Ihrer wertvollen Daten von defekten Speichermedien. Festplatten-Recovery, SSD-Datenrettung, USB-Stick Rettung.',
    category: 'Privatkunden',
    default_price: 89,
    unit: 'pauschal',
    is_active: true,
    sort_order: 5,
  },
  {
    name: 'IT-Sicherheit & Virenentfernung',
    description: 'Gründliche Entfernung von Schadsoftware und Einrichtung eines effektiven Schutzes. Malware-Entfernung, Ransomware-Hilfe, Antivirus-Setup, Firewall-Konfiguration.',
    category: 'Privatkunden',
    default_price: 45,
    unit: 'pauschal',
    is_active: true,
    sort_order: 6,
  },
  {
    name: 'PC-Aufrüstung',
    description: 'Mehr Leistung für Ihren Computer durch gezielte Hardware-Upgrades. SSD-Upgrade, RAM-Erweiterung, Grafikkarten-Einbau, CPU-Wechsel.',
    category: 'Privatkunden',
    default_price: 25,
    unit: 'Stunde',
    is_active: true,
    sort_order: 7,
  },
  {
    name: 'SSD-Upgrade',
    description: 'Austausch Ihrer alten Festplatte gegen eine schnelle SSD inkl. Datenübertragung.',
    category: 'Privatkunden',
    default_price: 49,
    unit: 'pauschal',
    is_active: true,
    sort_order: 8,
  },
  {
    name: 'RAM-Erweiterung',
    description: 'Aufrüstung des Arbeitsspeichers für bessere Performance (exkl. Hardware).',
    category: 'Privatkunden',
    default_price: 29,
    unit: 'pauschal',
    is_active: true,
    sort_order: 9,
  },
  {
    name: 'Grafikkarten-Einbau',
    description: 'Installation einer neuen Grafikkarte inkl. Treiberinstallation (exkl. Hardware).',
    category: 'Privatkunden',
    default_price: 39,
    unit: 'pauschal',
    is_active: true,
    sort_order: 10,
  },
  {
    name: 'Netzwerk & WLAN Einrichtung',
    description: 'Einrichtung und Optimierung Ihres Heimnetzwerks für beste Verbindung. Router-Setup, WLAN-Optimierung, Netzwerk-Sicherheit.',
    category: 'Privatkunden',
    default_price: 45,
    unit: 'pauschal',
    is_active: true,
    sort_order: 11,
  },
  {
    name: 'WLAN-Optimierung',
    description: 'Verbesserung Ihrer WLAN-Reichweite und -Geschwindigkeit.',
    category: 'Privatkunden',
    default_price: 39,
    unit: 'pauschal',
    is_active: true,
    sort_order: 12,
  },
  {
    name: 'PC Zusammenbau',
    description: 'Wir bauen Ihren Wunsch-PC nach Ihren Anforderungen zusammen – ob Gaming, Office oder Workstation. Individuelle Konfiguration, Windows-Installation, 12 Monate Garantie.',
    category: 'Privatkunden',
    default_price: 69,
    unit: 'pauschal',
    is_active: true,
    sort_order: 13,
  },
  {
    name: 'Leih-PC Service',
    description: 'Während Ihr Gerät repariert wird, arbeiten Sie einfach mit unserem Leihgerät weiter. Kostenloser Leih-PC, Datenübertragung, keine Ausfallzeit.',
    category: 'Privatkunden',
    default_price: 0,
    unit: 'pauschal',
    is_active: true,
    sort_order: 14,
  },
  {
    name: 'Laptop Reinigung',
    description: 'Professionelle Laptop-Reinigung für bessere Leistung und Kühlung.',
    category: 'Privatkunden',
    default_price: 30,
    unit: 'Stk.',
    is_active: true,
    sort_order: 15,
  },

  // =====================================================
  // GESCHÄFTSKUNDEN
  // =====================================================
  {
    name: 'IT-Support Remote',
    description: 'Zuverlässiger IT-Support per Fernwartung für Ihr Unternehmen.',
    category: 'Geschäftskunden',
    default_price: 50,
    unit: 'Stunde',
    is_active: true,
    sort_order: 100,
  },
  {
    name: 'IT-Support Vor-Ort',
    description: 'Zuverlässiger IT-Support direkt vor Ort bei Ihnen im Unternehmen.',
    category: 'Geschäftskunden',
    default_price: 75,
    unit: 'Stunde',
    is_active: true,
    sort_order: 101,
  },
  {
    name: 'IT-Support Flatrate',
    description: 'Support-Flatrate: Unlimitierter Support für eine monatliche Pauschale.',
    category: 'Geschäftskunden',
    default_price: 99,
    unit: 'Monat',
    is_active: true,
    sort_order: 102,
  },
  {
    name: 'Managed Services (5 User)',
    description: 'Komplette IT-Betreuung als monatliche Flatrate für bis zu 5 Benutzer. PC-Verwaltung, Server-Monitoring, Proaktive Wartung.',
    category: 'Geschäftskunden',
    default_price: 175,
    unit: 'Monat',
    is_active: true,
    sort_order: 103,
  },
  {
    name: 'Managed Services (10 User)',
    description: 'Komplette IT-Betreuung als monatliche Flatrate für bis zu 10 Benutzer.',
    category: 'Geschäftskunden',
    default_price: 350,
    unit: 'Monat',
    is_active: true,
    sort_order: 104,
  },
  {
    name: 'Managed Services (20 User)',
    description: 'Komplette IT-Betreuung als monatliche Flatrate für bis zu 20 Benutzer.',
    category: 'Geschäftskunden',
    default_price: 700,
    unit: 'Monat',
    is_active: true,
    sort_order: 105,
  },
  {
    name: 'Managed Services Pro User',
    description: 'Preis pro zusätzlichem Benutzer bei Managed Services.',
    category: 'Geschäftskunden',
    default_price: 35,
    unit: 'User/Monat',
    is_active: true,
    sort_order: 106,
  },
  {
    name: 'IT-Infrastruktur Setup',
    description: 'Server, Netzwerk und Cloud-Lösungen für Ihr Unternehmen. Server-Setup, Netzwerk-Konfiguration, Cloud-Migration.',
    category: 'Geschäftskunden',
    default_price: 299,
    unit: 'Projekt',
    is_active: true,
    sort_order: 107,
  },
  {
    name: 'Server-Installation',
    description: 'Installation und Konfiguration von Windows/Linux Servern.',
    category: 'Geschäftskunden',
    default_price: 499,
    unit: 'Projekt',
    is_active: true,
    sort_order: 108,
  },
  {
    name: 'Netzwerk-Installation',
    description: 'Planung und Einrichtung von Unternehmensnetzwerken.',
    category: 'Geschäftskunden',
    default_price: 399,
    unit: 'Projekt',
    is_active: true,
    sort_order: 109,
  },
  {
    name: 'IT-Sicherheit Audit',
    description: 'Umfassender Schutz für Ihre Unternehmensdaten und Systeme. Firewall-Setup, Security-Audit, Endpoint-Protection.',
    category: 'Geschäftskunden',
    default_price: 299,
    unit: 'Projekt',
    is_active: true,
    sort_order: 110,
  },
  {
    name: 'Firewall-Einrichtung',
    description: 'Installation und Konfiguration professioneller Firewalls.',
    category: 'Geschäftskunden',
    default_price: 249,
    unit: 'Projekt',
    is_active: true,
    sort_order: 111,
  },
  {
    name: 'Security-Audit',
    description: 'Umfassende Prüfung Ihrer IT-Sicherheit mit Bericht und Handlungsempfehlungen.',
    category: 'Geschäftskunden',
    default_price: 399,
    unit: 'Projekt',
    is_active: true,
    sort_order: 112,
  },
  {
    name: 'Office 365 Setup',
    description: 'Einrichtung von Microsoft Office 365 inkl. E-Mail-Migration und Benutzer-Setup.',
    category: 'Geschäftskunden',
    default_price: 199,
    unit: 'Projekt',
    is_active: true,
    sort_order: 113,
  },
  {
    name: 'Office 365 Lizenz',
    description: 'Microsoft Office 365 Business Lizenz pro Benutzer (monatlich).',
    category: 'Geschäftskunden',
    default_price: 12,
    unit: 'User/Monat',
    is_active: true,
    sort_order: 114,
  },
  {
    name: 'Cloud-Server Setup',
    description: 'Einrichtung von Cloud-Servern (Azure, AWS, etc.).',
    category: 'Geschäftskunden',
    default_price: 399,
    unit: 'Projekt',
    is_active: true,
    sort_order: 115,
  },
  {
    name: 'Cloud-Backup Einrichtung',
    description: 'Automatische Cloud-Backup-Lösung für Ihre Unternehmensdaten.',
    category: 'Geschäftskunden',
    default_price: 149,
    unit: 'Projekt',
    is_active: true,
    sort_order: 116,
  },
  {
    name: 'Enterprise WLAN Setup',
    description: 'Enterprise-Netzwerke, VPN und strukturierte Verkabelung. WLAN-Setup, VPN-Lösungen, Verkabelung.',
    category: 'Geschäftskunden',
    default_price: 299,
    unit: 'Projekt',
    is_active: true,
    sort_order: 117,
  },
  {
    name: 'VPN-Einrichtung',
    description: 'Sichere VPN-Verbindung für Home-Office und Außendienstmitarbeiter.',
    category: 'Geschäftskunden',
    default_price: 199,
    unit: 'Projekt',
    is_active: true,
    sort_order: 118,
  },
  {
    name: 'Netzwerk-Verkabelung',
    description: 'Professionelle strukturierte Verkabelung (Cat6/Cat7) inkl. Patchpanel.',
    category: 'Geschäftskunden',
    default_price: 79,
    unit: 'Dose',
    is_active: true,
    sort_order: 119,
  },
  {
    name: 'IT-Beratung',
    description: 'Strategische IT-Beratung für Digitalisierung und Optimierung. IT-Strategie, Digitalisierung, DSGVO-Beratung.',
    category: 'Geschäftskunden',
    default_price: 89,
    unit: 'Stunde',
    is_active: true,
    sort_order: 120,
  },
  {
    name: 'DSGVO IT-Beratung',
    description: 'IT-seitige Beratung zur DSGVO-Konformität Ihrer Systeme.',
    category: 'Geschäftskunden',
    default_price: 399,
    unit: 'Projekt',
    is_active: true,
    sort_order: 121,
  },
  {
    name: 'Business-PC Setup',
    description: 'Business-PCs, Laptops und Workstations inkl. Setup. Volumen-Rabatte, Windows Pro, Installation inklusive.',
    category: 'Geschäftskunden',
    default_price: 69,
    unit: 'Stück',
    is_active: true,
    sort_order: 122,
  },
  {
    name: 'Arbeitsplatz-Einrichtung',
    description: 'Komplette Einrichtung eines Büro-Arbeitsplatzes inkl. PC, Peripherie und Software.',
    category: 'Geschäftskunden',
    default_price: 149,
    unit: 'Stück',
    is_active: true,
    sort_order: 123,
  },

  // =====================================================
  // WEBDESIGN
  // =====================================================
  {
    name: 'Website Template',
    description: 'Schnell & günstig: Professionelles Design auf Basis bewährter Templates. Fertige Design-Vorlage, Ihre Texte & Bilder, bis zu 5 Seiten, Mobile-optimiert, Kontaktformular, SSL-Zertifikat. Live in 5-7 Tagen!',
    category: 'Webdesign',
    default_price: 599,
    unit: 'Projekt',
    is_active: true,
    sort_order: 200,
  },
  {
    name: 'Website Starter',
    description: 'Ideal für Selbstständige und kleine Unternehmen. Individuelles Design, bis zu 5 Seiten, Responsive Design, Kontaktformular, Basis SEO, 1 Monat Support.',
    category: 'Webdesign',
    default_price: 999,
    unit: 'Projekt',
    is_active: true,
    sort_order: 201,
  },
  {
    name: 'Website Business',
    description: 'Für wachsende Unternehmen mit mehr Anforderungen. Premium Design, bis zu 10 Seiten, CMS (Content Management), Erweiterte SEO, Google Analytics, Blog-Funktion, 3 Monate Support.',
    category: 'Webdesign',
    default_price: 1999,
    unit: 'Projekt',
    is_active: true,
    sort_order: 202,
  },
  {
    name: 'Website Enterprise',
    description: 'Individuelle Lösungen für anspruchsvolle Projekte. Komplett individuell, Unbegrenzte Seiten, E-Commerce möglich, Premium SEO Paket, Performance-Optimierung, API-Integrationen, 12 Monate Support.',
    category: 'Webdesign',
    default_price: 4999,
    unit: 'Projekt',
    is_active: true,
    sort_order: 203,
  },
  {
    name: 'SEO-Optimierung Basis',
    description: 'Basis SEO-Optimierung: Meta-Tags, Seitentitel, lokale SEO.',
    category: 'Webdesign',
    default_price: 199,
    unit: 'Projekt',
    is_active: true,
    sort_order: 204,
  },
  {
    name: 'SEO-Optimierung Premium',
    description: 'Umfassende SEO-Optimierung inkl. Content-Strategie und Backlink-Aufbau.',
    category: 'Webdesign',
    default_price: 499,
    unit: 'Monat',
    is_active: true,
    sort_order: 205,
  },
  {
    name: 'Website-Wartung',
    description: 'Monatliche Wartung, Updates, Backups und Sicherheits-Checks.',
    category: 'Webdesign',
    default_price: 79,
    unit: 'Monat',
    is_active: true,
    sort_order: 206,
  },
  {
    name: 'Logo-Design',
    description: 'Professionelles Logo-Design mit 3 Entwürfen.',
    category: 'Webdesign',
    default_price: 299,
    unit: 'Projekt',
    is_active: true,
    sort_order: 207,
  },
  {
    name: 'Content-Erstellung',
    description: 'Professionelle Texterstellung für Ihre Website (pro Seite).',
    category: 'Webdesign',
    default_price: 99,
    unit: 'Seite',
    is_active: true,
    sort_order: 208,
  },
  {
    name: 'Foto-Shooting',
    description: 'Professionelles Foto-Shooting für Ihre Website (halber Tag).',
    category: 'Webdesign',
    default_price: 399,
    unit: 'pauschal',
    is_active: true,
    sort_order: 209,
  },
  {
    name: 'Google My Business Setup',
    description: 'Professionelle Einrichtung und Optimierung Ihres Google My Business Profils.',
    category: 'Webdesign',
    default_price: 149,
    unit: 'Projekt',
    is_active: true,
    sort_order: 210,
  },
  {
    name: 'SSL-Zertifikat Einrichtung',
    description: 'Installation und Konfiguration von SSL-Zertifikaten.',
    category: 'Webdesign',
    default_price: 49,
    unit: 'Projekt',
    is_active: true,
    sort_order: 211,
  },
  {
    name: 'Website-Migration',
    description: 'Umzug Ihrer Website auf einen neuen Server/Hoster.',
    category: 'Webdesign',
    default_price: 249,
    unit: 'Projekt',
    is_active: true,
    sort_order: 212,
  },

  // =====================================================
  // SONSTIGES
  // =====================================================
  {
    name: 'Anfahrt Ansbach',
    description: 'Anfahrtspauschale innerhalb Ansbach (kostenlos).',
    category: 'Sonstiges',
    default_price: 0,
    unit: 'pauschal',
    is_active: true,
    sort_order: 300,
  },
  {
    name: 'Anfahrt Nürnberg',
    description: 'Anfahrtspauschale innerhalb Nürnberg.',
    category: 'Sonstiges',
    default_price: 15,
    unit: 'pauschal',
    is_active: true,
    sort_order: 301,
  },
  {
    name: 'Anfahrt bis 25km',
    description: 'Anfahrtspauschale im Umkreis von 25km.',
    category: 'Sonstiges',
    default_price: 25,
    unit: 'pauschal',
    is_active: true,
    sort_order: 302,
  },
  {
    name: 'Anfahrt bis 50km',
    description: 'Anfahrtspauschale im Umkreis von 50km.',
    category: 'Sonstiges',
    default_price: 45,
    unit: 'pauschal',
    is_active: true,
    sort_order: 303,
  },
  {
    name: 'Express-Service 24h',
    description: 'Bevorzugte Bearbeitung innerhalb 24 Stunden.',
    category: 'Sonstiges',
    default_price: 49,
    unit: 'pauschal',
    is_active: true,
    sort_order: 304,
  },
  {
    name: 'Express-Service Same-Day',
    description: 'Bearbeitung am selben Tag (nach Verfügbarkeit).',
    category: 'Sonstiges',
    default_price: 99,
    unit: 'pauschal',
    is_active: true,
    sort_order: 305,
  },
  {
    name: 'Abholung & Lieferung',
    description: 'Kostenlose Abholung und Rücklieferung innerhalb Ansbach.',
    category: 'Sonstiges',
    default_price: 0,
    unit: 'pauschal',
    is_active: true,
    sort_order: 306,
  },
  {
    name: 'Datenübertragung',
    description: 'Übertragung Ihrer Daten von altem auf neues Gerät.',
    category: 'Sonstiges',
    default_price: 39,
    unit: 'pauschal',
    is_active: true,
    sort_order: 307,
  },
  {
    name: 'Software-Installation',
    description: 'Installation von Standard-Software (Office, Browser, etc.).',
    category: 'Sonstiges',
    default_price: 29,
    unit: 'Stunde',
    is_active: true,
    sort_order: 308,
  },
  {
    name: 'Schulung & Einweisung',
    description: 'Individuelle Schulung zur PC-Bedienung oder Software (pro Stunde).',
    category: 'Sonstiges',
    default_price: 69,
    unit: 'Stunde',
    is_active: true,
    sort_order: 309,
  },
];
