export interface BlogArticle {
  slug: string;
  title: string;
  description: string;
  category: "pc-reparatur" | "it-sicherheit" | "it-unternehmen" | "webdesign" | "tipps";
  categoryLabel: string;
  publishDate: string;
  readTime: string;
  content: BlogSection[];
}

export interface BlogSection {
  type: "paragraph" | "heading" | "list" | "tip";
  text?: string;
  items?: string[];
}

export const BLOG_CATEGORIES = [
  { slug: "alle", label: "Alle Artikel" },
  { slug: "pc-reparatur", label: "PC-Reparatur" },
  { slug: "it-sicherheit", label: "IT-Sicherheit" },
  { slug: "it-unternehmen", label: "IT für Unternehmen" },
  { slug: "webdesign", label: "Webdesign" },
  { slug: "tipps", label: "Tipps & Tricks" },
];

export const BLOG_ARTICLES: BlogArticle[] = [
  {
    slug: "pc-startet-nicht-ursachen-loesungen",
    title: "PC startet nicht: 12 häufige Ursachen und Lösungen",
    description: "Ihr PC startet nicht mehr? Hier finden Sie die 12 häufigsten Ursachen und konkrete Lösungsansätze – vom lockeren Kabel bis zum defekten Mainboard.",
    category: "pc-reparatur",
    categoryLabel: "PC-Reparatur",
    publishDate: "2026-03-01",
    readTime: "8 Min.",
    content: [
      { type: "paragraph", text: "Ein PC der nicht startet ist eines der häufigsten Probleme, mit denen wir als IT-Service konfrontiert werden. Die Ursachen reichen von trivialen Stromversorgungsproblemen bis zu ernsthaften Hardware-Defekten. In diesem Ratgeber zeigen wir Ihnen die 12 häufigsten Ursachen – und was Sie selbst tun können, bevor Sie professionelle Hilfe brauchen." },
      { type: "heading", text: "1. Stromversorgung prüfen" },
      { type: "paragraph", text: "Klingt banal, ist aber die häufigste Ursache: Ein lockeres Stromkabel, eine defekte Steckdosenleiste oder ein ausgeschalteter Netzschalter am Netzteil. Prüfen Sie als Erstes, ob alle Kabel fest sitzen und Strom ankommt." },
      { type: "heading", text: "2. Monitor-Verbindung überprüfen" },
      { type: "paragraph", text: "Manchmal startet der PC tatsächlich – aber der Monitor zeigt nichts an. Prüfen Sie HDMI/DisplayPort-Kabel und ob der Monitor auf dem richtigen Eingang ist." },
      { type: "heading", text: "3. RAM-Module neu einsetzen" },
      { type: "paragraph", text: "Lose RAM-Module verhindern den Start komplett. Öffnen Sie das Gehäuse, entfernen Sie die RAM-Riegel vorsichtig und setzen Sie sie fest wieder ein – bis es klickt." },
      { type: "heading", text: "4. BIOS/CMOS-Batterie" },
      { type: "paragraph", text: "Eine leere CMOS-Batterie (CR2032) kann dazu führen, dass der PC nicht mehr startet oder in einer Boot-Schleife hängt. Kosten für eine neue Batterie: unter 3€." },
      { type: "heading", text: "5. Festplatte/SSD defekt" },
      { type: "paragraph", text: "Wenn der PC zwar angeht aber nicht ins Betriebssystem bootet, kann die Festplatte defekt sein. Klickende Geräusche bei HDDs sind ein deutliches Warnsignal." },
      { type: "heading", text: "6. Überhitzung" },
      { type: "paragraph", text: "Verstaubte Lüfter und ausgetrocknete Wärmeleitpaste führen zu Überhitzung. Der PC schaltet sich dann als Schutzmaßnahme ab oder startet gar nicht erst." },
      { type: "heading", text: "7. Netzteil defekt" },
      { type: "paragraph", text: "Ein defektes Netzteil ist eine häufige Ursache, besonders bei älteren PCs. Symptome: PC geht gar nicht an, oder startet kurz und schaltet sofort wieder ab." },
      { type: "heading", text: "8. Mainboard-Defekt" },
      { type: "paragraph", text: "Aufgeblähte Kondensatoren, Beschädigungen durch Überspannung oder Alterung können das Mainboard außer Gefecht setzen. Hier hilft meist nur professionelle Diagnose." },
      { type: "heading", text: "9. Windows beschädigt" },
      { type: "paragraph", text: "Fehlgeschlagene Updates oder Softwarefehler können Windows am Start hindern. Oft hilft ein Start im abgesicherten Modus oder eine Systemreparatur." },
      { type: "heading", text: "10. Grafikkarte lose oder defekt" },
      { type: "paragraph", text: "Eine lose Grafikkarte verhindert die Bildausgabe. Setzen Sie die Karte neu ein und prüfen Sie, ob alle Stromanschlüsse verbunden sind." },
      { type: "heading", text: "11. USB-Gerät blockiert Boot" },
      { type: "paragraph", text: "Ein angeschlossener USB-Stick oder externe Festplatte kann den Bootvorgang stören. Entfernen Sie alle USB-Geräte und versuchen Sie es erneut." },
      { type: "heading", text: "12. CPU-Probleme" },
      { type: "paragraph", text: "Seltener, aber möglich: Ein überhitzter oder defekter Prozessor. Oft durch unzureichende Kühlung verursacht." },
      { type: "heading", text: "Wann Sie professionelle Hilfe brauchen" },
      { type: "paragraph", text: "Wenn einfache Maßnahmen wie Kabel-Check und RAM-Neueinsetzen nicht helfen, ist professionelle Diagnose sinnvoll. Bei Petasync analysieren wir das Problem kostenlos bei Reparaturauftrag – und Sie bekommen einen Leih-PC, damit Sie in der Zwischenzeit weiterarbeiten können." },
      { type: "tip", text: "Unser Tipp: Regelmäßige Wartung (Reinigung, Updates, Backup) verhindert die meisten PC-Probleme. Unsere Basis-Wartung gibt es ab 25€." },
    ],
  },
  {
    slug: "laptop-ueberhitzt-was-tun",
    title: "Laptop überhitzt: 7 Sofortmaßnahmen und langfristige Lösungen",
    description: "Ihr Laptop wird heiß und laut? Erfahren Sie, warum Laptops überhitzen und was Sie sofort dagegen tun können – plus professionelle Lösungen.",
    category: "pc-reparatur",
    categoryLabel: "PC-Reparatur",
    publishDate: "2026-02-25",
    readTime: "6 Min.",
    content: [
      { type: "paragraph", text: "Ein überhitzter Laptop ist nicht nur nervig – er kann auch die Hardware dauerhaft beschädigen. Der Prozessor drosselt seine Leistung (Throttling), das System wird langsam, und im schlimmsten Fall schaltet sich das Gerät einfach ab. Hier erfahren Sie, was Sie sofort tun können." },
      { type: "heading", text: "Warum überhitzt mein Laptop?" },
      { type: "list", items: ["Verstaubte Lüftungsschlitze und Lüfter", "Ausgetrocknete Wärmeleitpaste (nach 2-3 Jahren üblich)", "Zu viele Programme gleichzeitig geöffnet", "Weiche Unterlage blockiert Luftzirkulation (Bett, Sofa)", "Malware die CPU dauerhaft belastet", "Defekter Lüfter", "Hohe Umgebungstemperatur"] },
      { type: "heading", text: "7 Sofortmaßnahmen" },
      { type: "paragraph", text: "1. Laptop auf harte, ebene Fläche stellen – niemals auf Decken oder Kissen. 2. Lüftungsschlitze mit Druckluft reinigen (von außen). 3. Unnötige Programme schließen – Task-Manager (Ctrl+Shift+Esc) zeigt CPU-Auslastung. 4. Energiesparplan auf 'Ausbalanciert' setzen statt 'Höchstleistung'. 5. Laptop-Kühler (Cooling Pad) verwenden – ab 15€. 6. Browser-Tabs reduzieren – jeder Tab verbraucht RAM und CPU. 7. Windows-Updates installieren – oft enthalten Treiber-Updates für bessere Kühlung." },
      { type: "heading", text: "Langfristige Lösungen" },
      { type: "paragraph", text: "Wenn die Sofortmaßnahmen nicht helfen, ist eine professionelle Reinigung nötig. Dabei wird der Laptop geöffnet, der Lüfter gereinigt, alte Wärmeleitpaste entfernt und neue aufgetragen. Das senkt die Temperatur oft um 10-20°C." },
      { type: "tip", text: "Unsere PC-Reinigung mit Wärmeleitpasten-Erneuerung gibt es ab 25€. Danach läuft Ihr Laptop wieder leise und kühl." },
    ],
  },
  {
    slug: "it-sicherheit-kleine-unternehmen-checkliste",
    title: "IT-Sicherheit für kleine Unternehmen: Die ultimative Checkliste 2026",
    description: "Cyberangriffe treffen zunehmend KMU. Diese Checkliste zeigt die wichtigsten Maßnahmen für IT-Sicherheit in kleinen Unternehmen – praxisnah und umsetzbar.",
    category: "it-sicherheit",
    categoryLabel: "IT-Sicherheit",
    publishDate: "2026-02-20",
    readTime: "10 Min.",
    content: [
      { type: "paragraph", text: "43% aller Cyberangriffe richten sich gegen kleine und mittlere Unternehmen. Trotzdem haben viele KMU keine systematische IT-Sicherheitsstrategie. Diese Checkliste gibt Ihnen einen konkreten Fahrplan – von den absoluten Basics bis zu fortgeschrittenen Maßnahmen." },
      { type: "heading", text: "Stufe 1: Die absoluten Basics" },
      { type: "list", items: ["Alle Systeme auf aktuellem Patch-Stand halten (Windows, Software, Router)", "Starke, einzigartige Passwörter + Passwort-Manager (z.B. Bitwarden, 1Password)", "Zwei-Faktor-Authentifizierung (2FA) für alle wichtigen Zugänge", "Regelmäßige Backups – 3-2-1-Regel: 3 Kopien, 2 Medien, 1 offsite", "Antivirus-Software auf allen Endgeräten"] },
      { type: "heading", text: "Stufe 2: Netzwerk absichern" },
      { type: "list", items: ["Firewall aktiv und korrekt konfiguriert", "WLAN mit WPA3 verschlüsselt, Gästenetz getrennt", "VPN für Remote-Zugriffe", "Netzwerk-Segmentierung (kritische Systeme isolieren)", "Router-Firmware aktuell halten"] },
      { type: "heading", text: "Stufe 3: Mitarbeiter sensibilisieren" },
      { type: "list", items: ["Regelmäßige Schulungen zu Phishing und Social Engineering", "Klare Richtlinien für Passwörter und Datenzugriff", "Meldeprozess für verdächtige E-Mails etablieren", "Prinzip der minimalen Berechtigung (Least Privilege)"] },
      { type: "heading", text: "Stufe 4: Notfallplan" },
      { type: "list", items: ["Incident-Response-Plan dokumentieren", "Ansprechpartner für IT-Notfälle festlegen", "Backup-Wiederherstellung regelmäßig testen", "Cyber-Versicherung prüfen"] },
      { type: "tip", text: "Unser IT-Sicherheitscheck für Unternehmen identifiziert Schwachstellen und gibt konkrete Handlungsempfehlungen. Jetzt IT-Sicherheitsaudit anfragen." },
    ],
  },
  {
    slug: "was-kostet-eine-website-2026",
    title: "Was kostet eine Website 2026? Ehrlicher Preisvergleich",
    description: "Website-Kosten von 0€ bis 50.000€ – was ist realistisch? Ein ehrlicher Vergleich aller Optionen: Baukasten, Template, Agentur, Freelancer.",
    category: "webdesign",
    categoryLabel: "Webdesign",
    publishDate: "2026-02-15",
    readTime: "12 Min.",
    content: [
      { type: "paragraph", text: "Die Frage 'Was kostet eine Website?' ist die häufigste Frage die uns potenzielle Kunden stellen. Die ehrliche Antwort: Es kommt darauf an. Aber in diesem Artikel geben wir Ihnen einen konkreten Überblick über alle Optionen – mit echten Preisen und ohne Marketing-Blabla." },
      { type: "heading", text: "Option 1: Kostenlose Baukästen (0-20€/Monat)" },
      { type: "paragraph", text: "Wix, Jimdo, Squarespace – die bekanntesten Baukästen. Vorteil: Günstig und schnell. Nachteil: Begrenzte Anpassbarkeit, oft langsam, eingeschränkte SEO-Möglichkeiten. Die Subdomain (firma.wixsite.com) wirkt unprofessionell. Eigene Domain kostet extra." },
      { type: "heading", text: "Option 2: WordPress mit Theme (500-2.000€)" },
      { type: "paragraph", text: "WordPress ist das beliebteste CMS der Welt. Ein Premium-Theme (50-100€) plus professionelle Einrichtung kostet je nach Umfang 500-2.000€. Vorteil: Flexibel, gute SEO. Nachteil: Wartungsaufwand, Sicherheits-Updates nötig, kann langsam werden." },
      { type: "heading", text: "Option 3: Template-Website vom Profi (490-990€)" },
      { type: "paragraph", text: "Unsere Template-Websites starten bei 490€. Sie basieren auf modernen Technologien (React), sind ultraschnell und SEO-optimiert. Individualisierung auf Ihre Branche und Marke. Ideal für Handwerker, Restaurants, Praxen." },
      { type: "heading", text: "Option 4: Individuelle Website (1.500-5.000€)" },
      { type: "paragraph", text: "Komplett individuelles Design, maßgeschneiderte Funktionen, CMS-Integration. Unser Business-Paket ab 1.990€ bietet 10 Seiten, CMS, Blog und erweiterte SEO. Ideal für wachsende Unternehmen die sich abheben wollen." },
      { type: "heading", text: "Option 5: Enterprise/E-Commerce (5.000-50.000€+)" },
      { type: "paragraph", text: "Online-Shops, Web-Apps, komplexe Portale. Unser Enterprise-Paket startet bei 3.990€. Große Agenturen berechnen für vergleichbare Projekte 15.000-50.000€. Die Kosten hängen stark von Funktionsumfang und Komplexität ab." },
      { type: "heading", text: "Laufende Kosten nicht vergessen" },
      { type: "list", items: ["Domain: 10-15€/Jahr", "Hosting: 5-30€/Monat", "SSL-Zertifikat: Oft im Hosting inklusive", "Wartung & Updates: 20-100€/Monat (oder selbst machen)", "Content-Pflege: Je nach Aufwand"] },
      { type: "heading", text: "Unsere Empfehlung" },
      { type: "paragraph", text: "Für die meisten kleinen Unternehmen ist eine Template- oder Starter-Website der beste Einstieg: Professionell, bezahlbar, und Sie können später upgraden. Lieber eine gute 490€-Website als eine schlechte kostenlose." },
      { type: "tip", text: "Unsere Website-Pakete starten bei 490€ einmalig – inklusive SEO, mobilem Design und persönlicher Beratung. Schauen Sie sich unsere Branchen-Demos an." },
    ],
  },
  {
    slug: "managed-services-vs-break-fix",
    title: "Managed Services vs. Break-Fix: Was lohnt sich für Ihr Unternehmen?",
    description: "IT-Support nur bei Problemen oder proaktive Betreuung? Vergleich beider Modelle mit klarer Empfehlung für verschiedene Unternehmensgrößen.",
    category: "it-unternehmen",
    categoryLabel: "IT für Unternehmen",
    publishDate: "2026-02-10",
    readTime: "7 Min.",
    content: [
      { type: "paragraph", text: "Als IT-Dienstleister hören wir oft: 'Warum soll ich monatlich für IT bezahlen, wenn gerade alles funktioniert?' Die Antwort liegt im Unterschied zwischen reaktiver (Break-Fix) und proaktiver (Managed Services) IT-Betreuung." },
      { type: "heading", text: "Break-Fix: IT-Support nur bei Problemen" },
      { type: "paragraph", text: "Beim Break-Fix-Modell rufen Sie den IT-Service, wenn etwas kaputt ist. Sie zahlen pro Einsatz oder Stunde. Vorteil: Keine laufenden Kosten. Nachteil: Unberechenbare Ausgaben, Ausfallzeiten, und meist höhere Gesamtkosten langfristig." },
      { type: "heading", text: "Managed Services: Proaktive IT-Betreuung" },
      { type: "paragraph", text: "Bei Managed Services wird Ihre IT kontinuierlich überwacht, gewartet und optimiert – gegen eine feste Monatspauschale. Probleme werden erkannt und gelöst, bevor sie Ausfälle verursachen." },
      { type: "heading", text: "Kostenvergleich (Beispiel: 10 Arbeitsplätze)" },
      { type: "list", items: ["Break-Fix: Ø 2-3 Notfalleinsätze/Monat × 150-300€ = 300-900€/Monat (unberechenbar)", "Managed Services: Feste 349€/Monat inklusive Monitoring, Updates, Support, Vor-Ort-Besuche"] },
      { type: "heading", text: "Unsere Empfehlung" },
      { type: "paragraph", text: "Bis 3 Arbeitsplätze: Break-Fix kann ausreichen. Ab 5 Arbeitsplätzen: Managed Services sind fast immer wirtschaftlicher – und Sie können ruhig schlafen, weil jemand auf Ihre IT aufpasst." },
      { type: "tip", text: "Unsere Managed Services starten ab 149€/Monat für 1-5 Mitarbeiter. Inklusive kostenloser IT-Analyse als Einstieg." },
    ],
  },
  {
    slug: "windows-wird-langsam-sofortmassnahmen",
    title: "Windows wird langsam: 7 Sofortmaßnahmen ohne Neuinstallation",
    description: "Ihr Windows-PC wird immer langsamer? Diese 7 Maßnahmen beschleunigen Ihr System sofort – ohne Neuinstallation oder teure Software.",
    category: "tipps",
    categoryLabel: "Tipps & Tricks",
    publishDate: "2026-02-05",
    readTime: "5 Min.",
    content: [
      { type: "paragraph", text: "Ein langsamer PC ist frustrierend – aber eine Neuinstallation ist oft gar nicht nötig. Mit diesen 7 Maßnahmen machen Sie Ihr Windows wieder schnell." },
      { type: "heading", text: "1. Autostart ausmisten" },
      { type: "paragraph", text: "Drücken Sie Ctrl+Shift+Esc → Reiter 'Autostart'. Deaktivieren Sie alles, was Sie nicht beim PC-Start brauchen. Spotify, Teams, Dropbox – das kann alles manuell gestartet werden." },
      { type: "heading", text: "2. Temporäre Dateien löschen" },
      { type: "paragraph", text: "Windows-Taste + R → 'temp' eingeben → Enter → alles markieren → löschen. Dann nochmal mit '%temp%'. Das gibt oft mehrere GB frei." },
      { type: "heading", text: "3. Festplatten-Belegung prüfen" },
      { type: "paragraph", text: "Ist Ihre Systemfestplatte über 90% voll? Dann wird Windows drastisch langsamer. Verschieben Sie große Dateien auf eine externe Festplatte oder löschen Sie Unnötiges." },
      { type: "heading", text: "4. Visuelle Effekte reduzieren" },
      { type: "paragraph", text: "Systemsteuerung → System → Erweiterte Systemeinstellungen → Leistung → 'Für optimale Leistung anpassen'. Das beschleunigt besonders ältere PCs." },
      { type: "heading", text: "5. Malware-Check durchführen" },
      { type: "paragraph", text: "Windows Defender Vollscan + zusätzlich Malwarebytes (kostenlose Version). Versteckte Malware kann die CPU dauerhaft belasten." },
      { type: "heading", text: "6. Windows-Updates installieren" },
      { type: "paragraph", text: "Ausstehende Updates können Performance-Fixes enthalten. Einstellungen → Update → Jetzt nach Updates suchen." },
      { type: "heading", text: "7. SSD als Systemlaufwerk" },
      { type: "paragraph", text: "Der größte Einzeleffekt: Wenn Sie noch eine HDD als Systemlaufwerk haben, ist der Wechsel auf eine SSD der mit Abstand wirksamste Upgrade. Bootzeit von 2 Minuten auf 15 Sekunden." },
      { type: "tip", text: "SSD-Upgrade inklusive Windows-Migration gibt es bei uns ab 45€ (+ SSD-Kosten). Der Unterschied ist wie ein neuer PC." },
    ],
  },
];
