// Template Configuration
export const TEMPLATES = {
  handwerker: {
    id: 'handwerker',
    name: 'Handwerker',
    description: 'Für Elektriker, Klempner, Schreiner & Maler',
    category: 'Handwerk',
    colors: {
      primary: '#FF6B35',
      secondary: '#2D3142',
      accent: '#F4B860',
      background: '#F8F9FA',
      text: '#1A1A1A',
    },
    features: [
      'Rotierender Werkzeugkoffer im Hero',
      '3D-Werkzeuge mit Hover-Rotation',
      'Funken-Partikel-Effekt',
      'Before/After Slider mit 3D-Flip',
      'Online-Terminbuchung',
      'Notdienst-Banner',
      'Kostenrechner',
      'WhatsApp-Integration',
    ],
  },
  versicherung: {
    id: 'versicherung',
    name: 'Versicherungsberater',
    description: 'Seriös, vertrauensvoll & modern',
    category: 'Beratung',
    colors: {
      primary: '#1E3A8A',
      secondary: '#D4AF37',
      accent: '#3B82F6',
      background: '#FFFFFF',
      text: '#1F2937',
    },
    features: [
      'Animierter 3D-Schutzschild',
      'Netzwerk-Visualisierung',
      '3D-Datenvisualisierung',
      'Versicherungsrechner',
      'PDF-Ratgeber Download',
      'Live-Chat',
      'Video-Testimonials',
    ],
  },
  restaurant: {
    id: 'restaurant',
    name: 'Restaurant',
    description: 'Elegant, warm & appetitlich',
    category: 'Gastronomie',
    colors: {
      primary: '#8B1538',
      secondary: '#F4E4C1',
      accent: '#D4AF37',
      background: '#1A1A1A',
      text: '#F8F8F8',
    },
    features: [
      'Rotierende Food-Modelle',
      '3D-Teller mit Speisen',
      'Dampf/Rauch-Partikel-Effekt',
      'Online-Tischreservierung',
      'Menü-PDF-Download',
      'Instagram-Feed-Integration',
      'Allergen-Filter',
    ],
  },
  fitness: {
    id: 'fitness',
    name: 'Fitness/Gym',
    description: 'Energiegeladen & motivierend',
    category: 'Sport & Gesundheit',
    colors: {
      primary: '#00FF00',
      secondary: '#000000',
      accent: '#FF00FF',
      background: '#0A0A0A',
      text: '#FFFFFF',
    },
    features: [
      '3D-Hanteln/Gewichte',
      'Energie-Partikel-System',
      '3D-Body-Transformation-Viewer',
      'Online-Kursanmeldung',
      'Fortschritts-Tracker',
      'BMI/Kalorienkalkulator',
      'Virtual Gym Tour (360°)',
    ],
  },
  immobilien: {
    id: 'immobilien',
    name: 'Immobilien',
    description: 'Luxuriös, clean & spacious',
    category: 'Immobilien',
    colors: {
      primary: '#2C3E50',
      secondary: '#ECF0F1',
      accent: '#C9B037',
      background: '#FFFFFF',
      text: '#34495E',
    },
    features: [
      '3D-Hausmodell rotierbar',
      'Virtuelle Raumvisualisierung',
      '3D-Grundriss-Viewer',
      'Advanced Property Search',
      'Virtual Tour Integration',
      'Mortgage Calculator',
      'Neighborhood Insights',
    ],
  },
  fotograf: {
    id: 'fotograf',
    name: 'Fotograf',
    description: 'Kreativ, portfolio-first & emotional',
    category: 'Kreativ',
    colors: {
      primary: '#000000',
      secondary: '#FFFFFF',
      accent: '#FF6B6B',
      background: '#F5F5F5',
      text: '#2C2C2C',
    },
    features: [
      '3D-Kamera-Modell',
      'Floating Polaroid-Frames',
      '3D-Gallery mit Depth',
      'Fullscreen-Lightbox',
      'Gallery-Kategorien',
      'Client-Proofing-Area',
      'Booking-System',
    ],
  },
  friseur: {
    id: 'friseur',
    name: 'Friseur/Salon',
    description: 'Stylish, modern-trendy & chic',
    category: 'Beauty & Wellness',
    colors: {
      primary: '#E91E63',
      secondary: '#212121',
      accent: '#FFD700',
      background: '#FAFAFA',
      text: '#333333',
    },
    features: [
      'Rotierende Schere/Kamm',
      '3D-Produktflaschen',
      'Glitzer-Partikel-Effekt',
      'Online-Terminbuchung',
      'Style-Quiz',
      'Instagram-Feed',
      'Produkt-Shop',
    ],
  },
  autowerkstatt: {
    id: 'autowerkstatt',
    name: 'Autowerkstatt',
    description: 'Technisch, professionell & zuverlässig',
    category: 'Automotive',
    colors: {
      primary: '#C41E3A',
      secondary: '#1C1C1C',
      accent: '#FFB81C',
      background: '#ECECEC',
      text: '#2B2B2B',
    },
    features: [
      'Rotierendes Auto-Modell',
      '3D-Reifen mit Animation',
      'Motor-Teile schwebend',
      'Online-Terminbuchung',
      'Reparaturkostenrechner',
      'TÜV-Erinnerungsservice',
      'Ersatzteil-Anfrage',
    ],
  },
} as const;

export type TemplateId = keyof typeof TEMPLATES;

export const TEMPLATE_LIST = Object.values(TEMPLATES);
